library("tibble")
tibbledata<-as_data_frame(reviewrestuarant)
library(dplyr)
glimpse(reviewrestuarant)
class(reviewrestuarant)
dim(reviewrestuarant)
names(reviewrestuarant)
str(reviewrestuarant)
head(reviewrestuarant)
tail(reviewrestuarant)
summary(reviewrestuarant)
hist(reviewrestuarant$Liked)
hist(real_estate_db$COUNTYID)
library(SnowballC)
stem_words<-stemDocument(c("Raining", "Smiling","Playing" ))
print(stem_words)
